apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordinates-api

spec:

  replicas: 3
  
  selector:
    matchLabels:
      app: coordinates-api
  
  template:
    metadata:
      labels:
        app: coordinates-api

    spec:
      containers:
      - name: api
        image: roeyaverbuch/coordinates_api:v1
        
        ports:
        - containerPort: 8000

        env:
        - name: POSTGRES_HOST
          value: "postgres-0.postgres-svc"  
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "coordinates_db"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        
 
---
apiVersion: v1
kind: Service
metadata:
  name: coordinates-api-svc

spec:

  type: NodePort
  selector:
    app: coordinates-api
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080
